name: Test

on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-14
            name: MacOS 64
            laz-url: https://sourceforge.net/projects/lazarus/files/Lazarus%20macOS%20x86-64/Lazarus%202.2.2/Lazarus-2.2.2-0-x86_64-macosx.pkg
            fpc-url: |
              https://sourceforge.net/projects/lazarus/files/Lazarus%20macOS%20x86-64/Lazarus%202.2.2/fpc-3.2.2.intelarm64-macosx.dmg
              https://sourceforge.net/projects/lazarus/files/Lazarus%20macOS%20x86-64/Lazarus%202.2.2/fpc-src-3.2.2-20210709-macosx.dmg 

    steps:
      - uses: actions/checkout@v3.0.2
      
      - name: Test
        run: |
          uname -m

      - name: Install Lazarus
        uses: ./
        with:
          laz-url: ${{ matrix.config.laz-url }}
          fpc-url: ${{ matrix.config.fpc-url }}
      
      - name: Build Test
        run: |
          lazbuild --cpu=aarch64 --os=darwin test_lazarus.lpi
          
      - name: Run Test
        run: |
          ./test

